#!/bin/sh

# PROVIDE: weewx
# REQUIRE: DAEMON NETWORKING
# KEYWORD: shutdown

# weewx_enable: Enable the weewx service
#       Required: Yes
#       Default: "NO"
#
# weewx_user: The user that will run weewx
#       Required: Yes
#       Default: "weewx"
#
# weewx_group: The group that will run weewx
#       Required: Yes
#       Default: "weewx"
#
# weewx_venv: Weewx virtual environment
#       Required: Yes
#       Default: "/home/weewx"
#
# weewx_log_file: Where weewx will store logs
#       Required: Yes
#       Default: "/var/log/weewx.log"
#
# weewx_config_file: Path to weewx config file, including the file name.
#       Required: Yes
#       Default: "/home/weewx/weewx-data/weewx.conf"
#
# weewx_run_options: Other flags to pass to weewx
#       Required: No
#       Default: ""
#       Any flags that can be passed to `weewx` go here.
#

. /etc/rc.subr

name="weewx"
rcvar=weewx_enable

load_rc_config $name
: ${weewx_enable:="NO"}
: ${weewx_user:="weewx"}
: ${weewx_group:="weewx"}
: ${weewx_venv:="/home/weewx"}
: ${weewx_log_file:="/var/log/weewx.log"}
: ${weewx_config_file:="/home/weewx/weewx-data/weewx.conf"}
: ${weewx_run_options:=""}

pid_directory=/var/run/${name}
pidfile="${pid_directory}/${name}_child.pid"
ppidfile="${pid_directory}/${name}_daemon.pid"

weewx_args="--config ${weewx_config_file} --pidfile /dev/null"
weewx_cmd=${weewx_venv}/bin/weewxd
weewx_full_cmd="${weewx_cmd} ${weewx_args}"
weewx_chdir=`echo ~${weewx_user}`
weewx_env="VIRTUAL_ENV=${weewx_venv}"

start_precmd="${name}_prestart"

# We can't run daemon as weewx_user, so unset it.
# If we left it set, daemon would automatically run as weewx_user, and that won't work.
# However, we're going to want to have daemon run the subprocess as the user, so set a different variable that we can use.
weewx_username=${weewx_user}
unset weewx_user

command="/usr/sbin/daemon"
command_args="-u ${weewx_username} -t weewx -p ${pidfile} -P ${ppidfile} -o ${weewx_log_file} -H -f -r ${weewx_full_cmd} ${weewx_args} ${rc_flags}"

weewx_prestart()
{
        # Check if PID directory exists
        if [ ! -d ${pid_directory} ]; then
               install -d -o ${weewx_username} ${pid_directory}
        fi

        # Check that the log file exists and set permissions properly
        if [ ! -f ${weewx_log_file} ]; then
            touch ${weewx_log_file}
        fi
        chown ${weewx_username}:${weewx_group} ${weewx_log_file}
        chmod 640 ${weewx_log_file}

        # Check to find weewx executable
        if [ ! -x ${weewx_cmd} ]; then
		echo "weewx not executable at ${weewx_cmd}" && exit 1
        fi
}

stop_cmd="${name}_stop"
weewx_stop()
{
        echo "Stopping PID: $(cat ${ppidfile})"
        /bin/kill -9 $(cat ${ppidfile})
        echo "Stopping PID: $(cat ${pidfile})"
        /bin/kill -15 $(cat ${pidfile})
}

run_rc_command "$1"

